name: manage-azure-policy-09a7f1f3
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Deploy_Diagnostic_Settings_for_Network_Security_Groups_c9c29499-c1d1-4195-99bd-2ec9e3a9dc89/**'
#      - .github/workflows/manage-azure-policy-09a7f1f3.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_09a7f1f3}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Deploy_Diagnostic_Settings_for_Network_Security_Groups_c9c29499-c1d1-4195-99bd-2ec9e3a9dc89/**
